logo: TRAVELL
name: Angela Jadan
lead: Hello I am a nice travel blogger. I like food.
<<<<<<< HEAD

#about
title: Обо мне
desc: Съешь же ещё этих мягких французских булок, да выпей чаю.
      Съешь же ещё этих мягких французских булок, да выпей чаю.
      Съешь же ещё этих мягких французских булок, да выпей чаю.
      Съешь же ещё этих мягких французских булок, да выпей чаю.
=======
>>>>>>> 2ee423a1e94b121b4752ac7383c3814ce5679d4e
