backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "assets/unploads" # Media files will be stored in the repo under "assets/unploads"

collections:
  - name: "website-settings"
    label: "Глобальные настройки"
    files:
      - label: "Главная страница"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Логотип"
            name: "logo"
            widget: "string"
          - label: "Имя"
            name: "name"
            widget: "string"
          - label: "Краткая информация"
            name: "lead"
            widget: "string"
      - label: "Страница «Обо мне»"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Заголовок"
            name: "title"
            widget: "string"
          - label: "Краткое описание"
            name: "desc"
            widget: "string"