backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "/assets/uploads" # Media files will be stored in the repo under "assets/unploads"

collections:
  - name: "website-settings"
    label: "Глобальные настройки"
    files:
      - label: "Логотип, имя, краткая информация (Главная страница и «Обо мне»)"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Логотип"
            name: "logo"
            widget: "string"
          - label: "Имя"
            name: "name"
            widget: "string"
          - label: "Краткая информация"
            name: "lead"
            widget: "string"
          - label: "Заголовок «Обо мне»"
            name: "title"
            widget: "string"
          - label: "Краткая информация «Обо мне»"
            name: "desc"
            widget: "string"
  - name: "about-me-page"
    label: "Контент страницы «Обо мне»"
    files: 
      - label: "Редактировать страницу «Обо мне»"
        name: "about"
        file: "about.md"
        fields:
          - label: "Заголовок (который, отображается на вкладке)"
            name: "title"
            widget: "string"
          - label: "Контент всей страницы"
            name: "body"
            widget: "markdown"
  - name: "blog-posts"
    label: "Посты"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Layout"
        name: "slug"
        widget: "string"
      - label: "Заголовок"
        name: "title"
        widget: "string"
      - label: "Баннер"
        name: "banner"
        widget: "image"
      - label: "Описание"
        name: "description"
        widget: "string"
      - label: "Автор"
        name: "author"
        widget: "string"
      - label: "Контент всей страницы"
        name: "body"
        widget: "markdown"